# Generated by Django 6.1 on 2026-08-20 05:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Short intro shown above the page body.', max_length=200)),
                ('body', wagtail.fields.StreamField([('hero', 7), ('service_cards', 14), ('cta', 16), ('rich_content', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book a discovery call', 'max_length': 60, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Explore services', 'max_length': 60, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('subtitle', 2), ('primary_cta_label', 3), ('primary_cta_url', 4), ('secondary_cta_label', 5), ('secondary_cta_url', 4), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'What we build', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon key such as code, chart, bolt.', 'max_length': 30, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('intro', 2), ('cards', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 16: ('wagtail.blocks.StructBlock', [[('heading', 15), ('body', 2), ('button_label', 3), ('button_url', 4)]], {}), 17: ('marketing.blocks.RichContentBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3']})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Short intro shown above the page body.', max_length=200)),
                ('body', wagtail.fields.StreamField([('hero', 7), ('service_cards', 14), ('cta', 16), ('rich_content', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book a discovery call', 'max_length': 60, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Explore services', 'max_length': 60, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('subtitle', 2), ('primary_cta_label', 3), ('primary_cta_url', 4), ('secondary_cta_label', 5), ('secondary_cta_url', 4), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'What we build', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon key such as code, chart, bolt.', 'max_length': 30, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('intro', 2), ('cards', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 16: ('wagtail.blocks.StructBlock', [[('heading', 15), ('body', 2), ('button_label', 3), ('button_url', 4)]], {}), 17: ('marketing.blocks.RichContentBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3']})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, help_text='Short intro shown above the page body.', max_length=200)),
                ('body', wagtail.fields.StreamField([('hero', 7), ('service_cards', 14), ('cta', 16), ('rich_content', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 180}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book a discovery call', 'max_length': 60, 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Explore services', 'max_length': 60, 'required': False}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('title', 1), ('subtitle', 2), ('primary_cta_label', 3), ('primary_cta_url', 4), ('secondary_cta_label', 5), ('secondary_cta_url', 4), ('image', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'What we build', 'max_length': 120, 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 10: ('wagtail.blocks.TextBlock', (), {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional icon key such as code, chart, bolt.', 'max_length': 30, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('description', 10), ('icon', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('heading', 8), ('intro', 2), ('cards', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 16: ('wagtail.blocks.StructBlock', [[('heading', 15), ('body', 2), ('button_label', 3), ('button_url', 4)]], {}), 17: ('marketing.blocks.RichContentBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h2', 'h3']})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
