# Generated by Django 6.1 on 2026-08-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(help_text='Short description for cards and previews.')),
                ('body', models.TextField(help_text='Long-form project details.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('client', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='portfolio.tag')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
