# Generated by Django 6.1 on 2026-08-24 16:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_youtube_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/",
                validators=[core.utils.validate_image_file],
            ),
        ),
    ]
